### PR TITLE
usage of btp-setup-automator in command line tool style

### PR DESCRIPTION
**Pull request by andre68723**
Hi Rui,

thanks first for this valuable tool. I was looking for some time for something similar and happy to have found it now .
My intention is to use it to setup new DC using this tool and maintaining it in git.

Inspired by [ocrmypdf](https://ocrmypdf.readthedocs.io/en/latest/docker.html#docker) which also packages countless dependencies and tools -see [here](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/ocrmypdf.rb) I'd suggest to enable usage as commandline-tool. For this, I changed the `CMD` to `ENTRYPOINT` and added a bit documentation.

Open points:
* would the CMD->ENTRYPOINT change require a separate dockerimage which can still be used with VSC remote containers since it starts directly?
* the current invocation from outside always requires the files to be mapped to `data/` dir. Maybe the python can be changed to avoid this and come to a cleaner `$ docker_btpsa -parameterfile parameters.json -usecasefile usecase.json`

PS: this would also later on enable the separation of concerns, a repo for the CLI-like tool via Dockerimage and a repo only for the definitions itself.

Thanks, Andre

### CODE REVIEW

**Comment by rui1610** [comment]
Hi Andre, thanks a lot for your pull request. Having people using the tool and spending thoughts on how to make it better is something I highly appreciate. At the end that's how opensource projects work and flurish.

So far I think that I wouldn't like to change the current way how the script works. As you can see in the `integrationtests` folder we already use the command-line driven approach.
Check as well the Github actions we have pulled together for that purpose. Merging the code in the Dockerfile might break the current user experience.

In any case the idea is good. In fact I've started exactly with the separation that you are proposing. But while I've moved along it became difficult to explain the concept of separated repositories. That's why the use case files are in a separate `usecases` folder. 

I'll leave your PR open for now and let other colleagues like @lechnerc77 and @yevgentrukhin or @fabianleh share their thoughts on your proposal. At the end I don't want to make an incompatible in the code. So we'll have to see how we can manage this properly

Best,
Rui

**Comment by rui1610** [comment]
In addition I'd like to point out, that you can provide the parameters and usecase.json file as well as a link e.g. somewhere on github or other web pages. Checkout https://github.com/SAP-samples/btp-setup-automator/blob/main/integrationtests/parameterfiles/integrationtest02.json for an example.

**Comment by lechnerc77** [comment]
Hi Andre, 
I think your point is a valid usage or consumption scenario for the CLI. However your proposed change would remove the option to use the existing consumption scenarios due to the change from `CMD` to `ENTRYPOINT` in the `DOCKERFILE`.

I also think that the necessity to set an alias manually reduces the convenience that is intended by the change. 

If this request should be implemented, I would put the following tasks up for discussion:

- The variant with `ENTRYPOINT` is implemented in a dedicated `DOCKERFILE`
- The build must be adjusted to create an additional image (= extension of GH Actions)
- New scripts need to be provided that mimic the existing `run` scripts but execute the build or pull of the container and execute the docker run for the changed setup. Those need to be provided for `bash`, `PowerShell` and `cmd`.
- Documentation needs to be adjusted to describe the new setup and the usage of the new scripts

**Comment by andre68723** [comment]
Hi, 

yes, agreed with all comments. I assumed that adding a 2nd image would be the only option to stay aligned/compatible.
I'll see if I can make it work and extend as suggested.

@rui1610 you see any chance of easing that situation with the /data directory as described above? That would make it much easier to not have to map to data

**Comment by rui1610** [comment]
I think it would make things easier if you use the docker mount option (target / source as described in  https://docs.docker.com/storage/bind-mounts/ ) instead of using a volume.
This allows you to mount any local source folder to a folder inside the container. Do you want to give it a try?

**Comment by rui1610** [comment]
Hi @andre68723 , where you able to try out my proposal? Let me know in case we should discuss further or if I can close the PR.

**Comment by andre68723** [comment]
not yet, will do it after vacation. 

Can close it meanwhile, will raise it again later

**Comment by rui1610** [comment]
Ok. Will close it meanwhile. Have some great vacation!

**Pull request closed without merging**
