### PR TITLE
harden cf API Endpoint parsing from btp response

### PR DESCRIPTION
**Pull request by makeItFuckingSustainable**
As pointed out in [this slack comment](https://sap-btp.slack.com/archives/CCXF812E9/p1659430751327569), btp responses sometimes hold the keys 
(`Org Name`, `API Endpoint`, `Org ID`) 
and unfortunately sometimes they hold the keys with added colons as part of the key 
(`Org Name:`, `API Endpoint:`, `Org ID:`). 

This change hardens the api endpoint retrieval against this nonsense response behaviour.

### CODE REVIEW

**Comment by lechnerc77** [comment]
@makeItFuckingSustainable : Your GitHub handle is not in line with the Code of Conduct. I am therefore closing this PR without merging.

**Comment by makeItFuckingSustainable** [comment]
I'm sorry to hear that I'm not complying to the Code of Conduct. It is not my intend to offend or in any way disrespect anyone in this community.
Just for clarification, could you highlight how my username disrespects the Code of Conduct?

**Comment by lechnerc77** [comment]
The code states: 

>[...] Examples of unacceptable behavior include:
>The use of sexualized language or imagery, and sexual attention or advances of any kind [...]
 
Parts of your username fall into this category and can be considered offensive language usage

**Comment by makeItFuckingSustainable** [comment]
While I beg to differ, it is your repository and hence your playground.
Thanks for the clarification.

**Pull request closed without merging**
